version: '2'
services:
    minecraft-server:
        container_name: mc
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        tty: true
        stdin_open: true
        restart: always
        volumes:
            - ./data:/data
        environment:
            EULA: "TRUE"